# Generated by Django 3.2.8 on 2021-10-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_subscribe',
            field=models.BooleanField(default=False),
        ),
    ]
