# Generated by Django 3.2.8 on 2021-11-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='img',
            field=models.ImageField(default='user_img.png', upload_to='images/'),
        ),
    ]
