# Generated by Django 3.2.8 on 2021-11-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='c',
            field=models.CharField(default='a', max_length=3),
        ),
    ]
