# Generated by Django 3.2.8 on 2021-11-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_c'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='c',
        ),
    ]
