# Generated by Django 3.2.8 on 2021-11-04 21:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('genre', models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('drama', 'Drama'), ('comedy', 'Comedy'), ('romance', 'Romance'), ('horror', 'Horror'), ('noir', 'Noir'), ('sci-fi', 'Sci-Fi'), ('western', 'Western')], max_length=25)),
                ('director', models.CharField(max_length=250)),
                ('plot', models.TextField(max_length=250)),
                ('poster', models.ImageField(upload_to='images/')),
                ('release_date', models.DateField()),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('price', models.FloatField(default=7.99)),
                ('video', models.URLField()),
                ('views', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('reviewed_film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movie.film')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ManyToManyField(to='movie.Film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
