# Generated by Django 3.2.8 on 2021-11-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_film_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('drama', 'Drama'), ('comedy', 'Comedy'), ('romance', 'Romance'), ('horror', 'Horror'), ('noir', 'Noir'), ('sci-fi', 'Sci-Fi')], max_length=25),
        ),
    ]
